const { execSync } = require('child_process');

// Test the swaks command that would be generated by the email service
const testEmailCommand = `swaks --to "test@example.com" --server "smtp.gmail.com" --port "587" --h-Subject "Test Email" --body 'Test email body' --add-header "MIME-Version: 1.0" --add-header "Content-Type: text/html; charset=utf-8"`;

console.log('Testing swaks command:');
console.log(testEmailCommand);
console.log('\n--- Command Output ---');

try {
  const output = execSync(testEmailCommand, { encoding: 'utf8', timeout: 10000 });
  console.log(output);
} catch (error) {
  console.error('Error:', error.message);
  console.error('Stdout:', error.stdout);
  console.error('Stderr:', error.stderr);
}