import { Controller, Get, Req, Res } from '@nestjs/common';
import type { Request, Response } from 'express';
import { Public } from '../../auth/decorators/public.decorator';

@Controller('csrf')
export class CsrfController {
  @Get('token')
  @Public()
  getCsrfToken(@Req() req: Request, @Res() res: Response) {
    // The CSRF token is automatically generated by the middleware
    // and attached to the request object
    const token = (req as any).csrfToken();

    res.json({
      csrfToken: token,
      message: 'CSRF token generated successfully',
    });
  }
}