import { Controller, Get, Req, Res } from '@nestjs/common';
import type { Request, Response } from 'express';
import { Public } from '../../auth/decorators/public.decorator';

@Controller('csrf')
export class CsrfController {
  @Get('token')
  @Public()
  getCsrfToken(@Req() req: Request, @Res() res: Response) {
    console.log('CSRF Controller - getCsrfToken called');
    console.log('Request path:', req.path);
    console.log('Request method:', req.method);
    console.log('csrfToken function available:', typeof (req as any).csrfToken);

    try {
      // The CSRF token is automatically generated by the middleware
      // and attached to the request object
      const token = (req as any).csrfToken();
      console.log('CSRF token generated successfully:', token ? 'YES' : 'NO');

      res.json({
        csrfToken: token,
        message: 'CSRF token generated successfully',
      });
    } catch (error) {
      console.error('Error in getCsrfToken:', error);
      throw error;
    }
  }
}